### ISSUE TITLE
Play Google Drive offline files on Android

### ISSUE THREAD

**Issue by graymoment** [nicolasgarnier/drive-music-player#54]
Is it possible to play files that are pinned for offline use on an Android device? I have limited bandwidth available for mobile data access, and would like to play music from a Drive folder that is pinned to stay on the device without streaming it from the internet.

Currently, on my Android, if I click music that is pinned for offline use in the Drive app, it will go to Chrome to open the player, presumably streaming it from my online account.

**Comment by nicolasgarnier** [comment]
Unfortunately that's not possible with the this app because it's web based and it does not have access to the files saved locally on your android device. What you should do instead is open your offline files using a native app on your android device like VLC for instance or other music player you can find on the Play Store. 

Cheers!
